#!/usr/sbin/nft -f

flush ruleset

table inet filter {
        chain input {
                type filter hook input priority filter;

                iifname { "vmbr1", "vmbr2" } tcp dport { 22, 111, 3128, 8006 } drop
                iifname { "vmbr1", "vmbr2" } udp dport 111 drop
        }

        chain forward {
                type filter hook forward priority filter;
        }

        chain output {
                type filter hook output priority filter;
        }
}

table ip homelab_nat {
        chain postrouting {
                type nat hook postrouting priority srcnat;
                oifname "vmbr0" ip saddr 10.10.10.0/24 masquerade
                oifname "vmbr0" ip saddr 10.10.20.0/24 masquerade
        }
}
