chain=main
server=1
listen=1
bind=127.0.0.1
listenonion=1
proxy=127.0.0.1:9050
onlynet=onion
torcontrol=127.0.0.1:9051
discover=0
natpmp=0
dnsseed=0
prune=10000
dbcache=450
maxconnections=16
rpcbind=127.0.0.1
rpcallowip=127.0.0.1
rpcport=8332
rpccookiefile=/var/lib/bitcoind/.cookie
datadir=/var/lib/bitcoind
debuglogfile=/var/lib/bitcoind/debug.log
privatebroadcast=0
