apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-operator
  namespace: flux-system
spec:
  interval: 1h
  path: "./k8s/apps/flux-system/flux-operator/app"
  prune: false # never prune!
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: false # no flux ks dependents
