#!/bin/bash
set -e
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE ROLE "${MW_DB_USER}" LOGIN PASSWORD '${MW_DB_PASSWORD}';
    GRANT USAGE ON SCHEMA btc TO "${MW_DB_USER}";
    GRANT SELECT, INSERT, UPDATE ON ALL TABLES IN SCHEMA btc TO "${MW_DB_USER}";
    GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA btc TO "${MW_DB_USER}";
    ALTER DEFAULT PRIVILEGES IN SCHEMA btc GRANT SELECT, INSERT, UPDATE ON TABLES  TO "${MW_DB_USER}";
    ALTER DEFAULT PRIVILEGES IN SCHEMA btc GRANT USAGE,  SELECT ON SEQUENCES        TO "${MW_DB_USER}";
EOSQL