apiVersion: v1
kind: ConfigMap
metadata:
  name: "homepage-config"
data:
  bookmarks.yaml: ""
  kubernetes.yaml: |
    mode: cluster
    gateway: true
    ingress: false
    traefik: false
  services.yaml: ""
  settings.yaml: |
    cardBlur: xl
    target: _self
    language: de
    statusStyle: 'dot'
    quicklaunch:
      searchDescriptions: true
      hideInternetSearch: true
      hideVisitURL: true
    hideVersion: true
    hideErrors: true
    color: slate
    iconStyle: theme
    theme: dark
    title: Home
    disableCollapse: true
    layout:
      - Heimautomation:
          tab: Allgemeines
          style: row
          columns: 3
      - Medien:
          tab: Allgemeines
          style: row
          columns: 3
      - Überwachung:
          tab: Technik
          style: row
          columns: 3
      - Netzwerk:
          tab: Technik
          style: row
          columns: 3
      - Weitere:
          tab: Technik
          style: row
          columns: 3
      - Externe Geräte:
          tab: Technik
          style: row
          columns: 4
  widgets.yaml: |-
    - kubernetes:
        cluster:
          show: true
          cpu: true
          memory: true
          showLabel: false
          label: "cluster"
        nodes:
          show: false
    - datetime:
        text_size: xl
        format:
          timeStyle: short
