apiVersion: v1
kind: ConfigMap
metadata:
  name: bitcoin-config
  namespace: bitcoin
data:
  bitcoin.conf: |
    regtest=1
    server=1
    txindex=1

    # RPC auth comes from env in the container wrapper (see StatefulSet)
    rpcallowip=0.0.0.0/0
    rpcbind=0.0.0.0

    fallbackfee=0.0001
    zmqpubrawtx=tcp://0.0.0.0:28332
    zmqpubrawblock=tcp://0.0.0.0:28333
