# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cilium
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: cilium
  values:
    bpf:
      masquerade: true
      datapathMode: netkit
      preallocateMaps: true
      distributedLRU:
        enabled: true
    bpfClockProbe: true
    operator:
      replicas: 1 # single node
    hubble:
      enabled: false
    nodeIPAM:
      enabled: true
    envoy:
      enabled: false
    rollOutCiliumPods: true
    # ipv4NativeRoutingCIDR: 10.0.0.0/16 TODO
    # routingMode: native
    kubeProxyReplacement: true
    # KubePrism
    k8sServiceHost: localhost
    k8sServicePort: 7445
    pmtuDiscovery:
      enabled: true
    # Enable encryption for all traffic, including node-to-node traffic, which is not encrypted by default.
    encryption:
      enabled: true
      type: wireguard
    # Override securityContext to allow running cilium on talos as talos does not support SYS_MODULE
    securityContext:
      capabilities:
        ciliumAgent:
          - CHOWN
          - KILL
          - NET_ADMIN
          - NET_RAW
          - IPC_LOCK
          - SYS_ADMIN
          - SYS_RESOURCE
          - DAC_OVERRIDE
          - FOWNER
          - SETGID
          - SETUID
        cleanCiliumState:
          - NET_ADMIN
          - SYS_ADMIN
          - SYS_RESOURCE
    cgroup:
      autoMount:
        enabled: false
      hostRoot: /sys/fs/cgroup
