---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: paperless
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-fields
  target:
    name: paperless-secret
    creationPolicy: Owner
    template:
      data:
        PAPERLESS_ADMIN_USER: "{{ .paperless_admin_username }}"
        PAPERLESS_ADMIN_PASSWORD: "{{ .paperless_admin_password }}"
        PAPERLESS_SECRET_KEY: "{{ .paperless_config_secret_key }}"
        PAPERLESS_SOCIALACCOUNT_PROVIDERS: |
          {
            "openid_connect": {
                "OAUTH_PKCE_ENABLED": "True",
                "APPS": [
                    {
                        "provider_id": "kanidm",
                        "name": "Kanidm",
                        "client_id": "paper",
                        "secret": "{{ .paperless_oauth_client_secret }}",
                        "settings": {
                            "server_url": "https://idm.uni.lucadev.de
/oauth2/openid/paper/.well-known/openid-configuration"
                        }
                    }
                ]
            }
          }
        PAPERLESS_GMAIL_OAUTH_CLIENT_ID: "{{ .paperless_gmail_oauth_client_id }}"
        PAPERLESS_GMAIL_OAUTH_CLIENT_SECRET: "{{ .paperless_gmail_oauth_client_token }}"
  data:
    - secretKey: paperless_admin_username
      remoteRef:
        key: paperless
        property: admin_username
    - secretKey: paperless_admin_password
      remoteRef:
        key: paperless
        property: admin_password
    - secretKey: paperless_config_secret_key
      remoteRef:
        key: paperless
        property: config_secret_key
    - secretKey: paperless_oauth_client_secret
      remoteRef:
        key: 875d4fc0-6bc1-493c-a8bb-b07c00c08ee1
        property: paperless_oauth_client_secret
    - secretKey: paperless_gmail_oauth_client_id
      remoteRef:
        key: paperless
        property: gmail_oauth_client_id
    - secretKey: paperless_gmail_oauth_client_token
      remoteRef:
        key: paperless
        property: gmail_oauth_client_key
