# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: paperless
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  values:
    controllers:
      paperless:
        type: statefulset
        containers:
          app:
            image:
              repository: ghcr.io/paperless-ngx/paperless-ngx
              tag: 2.20.13
            envFrom:
              - secretRef:
                  name: paperless-secret
              - configMapRef:
                  name: paperless-configmap
            resources:
              requests:
                cpu: 11m
                memory: 512M
              limits:
                cpu: 1000m
                memory: 3Gi
        annotations:
          reloader.stakater.com/auto: "true"
        statefulset:
          volumeClaimTemplates:
            - name: data
              accessMode: ReadWriteOnce
              size: 15Gi
              storageClass: cached-dualreplica
              globalMounts:
                - path: /data/local
    service:
      app:
        controller: paperless
        ports:
          http:
            port: 8000
    persistence:
      paperless-ingest:
        type: hostPath
        hostPath: /tmp/paperless-ingest
        hostPathType: DirectoryOrCreate
        globalMounts:
          - path: /data/consume
      export:
        globalMounts:
          - path: /data/export
        type: persistentVolumeClaim
        accessMode: ReadWriteOnce
        storageClass: ssd-singlereplica
        size: 1G
    route:
      app:
        hostnames:
          - paperless.uni.lucadev.de
        parentRefs:
          - name: envoy
            namespace: networking
            sectionName: https
        rules:
          - backendRefs:
              - name: app
                port: 8000
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/description: Dokumenten Verwaltungs System
          gethomepage.dev/group: Medien
          gethomepage.dev/icon: paperless-ngx
          gethomepage.dev/name: PaperlessNGX
          gethomepage.dev/weight: "-80"
